apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/hsts_header: max-age=63072000
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: grpc-gateway-sample
  name: grpc-gateway-sample
spec:
  path: /
  port:
    targetPort: http-3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: grpc-gateway-sample
    weight: 100
  wildcardPolicy: None
status: {}
---
