apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: tekton-results-tls
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: grpc-gateway-sample-gosi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: grpc-gateway-sample-gosi
    app.kubernetes.io/part-of: grpc-gateway-sample
    app.kubernetes.io/version: devel
  name: grpc-gateway-sample-gosi
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  - name: http-3001
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: grpc-gateway-sample-gosi
    app.kubernetes.io/name: tekton-results-api-14
status:
  loadBalancer: {}
